package trash;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author OSM
 */
public class UserRevRateView extends javax.swing.JFrame {

    Connection con;
    Statement stat;
    ResultSet res;

    int movieID = 3;//TODO replace with id from movie table
    int userID = 1;//TODO replace with id of logged in user

    //statment to fetch data of userRevRateView
    PreparedStatement joinStatement;
    PreparedStatement fetchNameStatement;

    // variables passed from the view review button to the userRevRateVeiw 
    int rate;
    int uID;//change later to userID 
    String review;
    int count;// to count the number of reviews
    int currentRevPage=0;
    String name; //name of user
    //result sets for the userRevRateView
    ResultSet resJoin;
    ResultSet resName;

    /**
     * Creates new form UserRevRate
     */
    public UserRevRateView() {
        initComponents();
        getConnection();
        //transparent background
        jtextUserName.setBackground(new java.awt.Color(0, 0, 0, 1));
        jtextUserRate.setBackground(new java.awt.Color(0, 0, 0, 1));
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setBorder(null);
        jScrollPane1.setViewportBorder(null);
        jTextAreaReview.setBorder(null);
        jTextAreaReview.setBackground(new java.awt.Color(0, 0, 0, 1));

        jTextAreaReview.setLineWrap(true); //for adding new line instead of scrolling
        jTextAreaReview.setWrapStyleWord(true);

    }

    void getConnection() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema", "root", "root");
        } catch (SQLException e) {
            e.printStackTrace();
        }
        System.out.println("connected");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelReview = new javax.swing.JLabel();
        jLabelReviewCount = new javax.swing.JLabel();
        jLabeCurrentReview = new javax.swing.JLabel();
        jLabeSlash = new javax.swing.JLabel();
        jLabelRate = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jButtonViewReviews = new javax.swing.JButton();
        jButtonNextReview = new javax.swing.JButton();
        jtextUserName = new javax.swing.JTextField();
        jtextUserRate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaReview = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelReview.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelReview.setForeground(new java.awt.Color(255, 255, 255));
        jLabelReview.setText("Review");
        jPanel1.add(jLabelReview, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 190, 30));

        jLabelReviewCount.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelReviewCount.setForeground(new java.awt.Color(255, 255, 255));
        jLabelReviewCount.setText("Max");
        jPanel1.add(jLabelReviewCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, -1, 40));

        jLabeCurrentReview.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabeCurrentReview.setForeground(new java.awt.Color(255, 255, 255));
        jLabeCurrentReview.setText("1");
        jPanel1.add(jLabeCurrentReview, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, -1, 40));

        jLabeSlash.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabeSlash.setForeground(new java.awt.Color(255, 255, 255));
        jLabeSlash.setText("/");
        jPanel1.add(jLabeSlash, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, -1, 40));

        jLabelRate.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelRate.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRate.setText("Rating:");
        jPanel1.add(jLabelRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 140, 40));

        jSeparator8.setBackground(new java.awt.Color(200, 200, 200));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 400, -1));

        jSeparator5.setBackground(new java.awt.Color(200, 200, 200));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 400, 10));

        jSeparator7.setBackground(new java.awt.Color(200, 200, 200));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 400, 10));

        jButtonViewReviews.setBackground(new java.awt.Color(115, 0, 0));
        jButtonViewReviews.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonViewReviews.setForeground(new java.awt.Color(200, 200, 200));
        jButtonViewReviews.setText("View Reviews");
        jButtonViewReviews.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonViewReviews.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewReviewsActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonViewReviews, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 70, 40));

        jButtonNextReview.setBackground(new java.awt.Color(115, 0, 0));
        jButtonNextReview.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonNextReview.setForeground(new java.awt.Color(200, 200, 200));
        jButtonNextReview.setText("Next Review");
        jButtonNextReview.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNextReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextReviewActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNextReview, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 180, 40));

        jtextUserName.setEditable(false);
        jtextUserName.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jtextUserName.setForeground(new java.awt.Color(255, 255, 255));
        jtextUserName.setText("User Name");
        jtextUserName.setBorder(null);
        jtextUserName.setOpaque(false);
        jtextUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextUserNameActionPerformed(evt);
            }
        });
        jPanel1.add(jtextUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 370, 30));

        jtextUserRate.setEditable(false);
        jtextUserRate.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jtextUserRate.setForeground(new java.awt.Color(255, 255, 255));
        jtextUserRate.setText("10");
        jtextUserRate.setBorder(null);
        jtextUserRate.setOpaque(false);
        jtextUserRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextUserRateActionPerformed(evt);
            }
        });
        jPanel1.add(jtextUserRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 50, 40));

        jScrollPane1.setFocusable(false);
        jScrollPane1.setOpaque(false);

        jTextAreaReview.setEditable(false);
        jTextAreaReview.setColumns(20);
        jTextAreaReview.setFont(new java.awt.Font("Palatino Linotype", 3, 20)); // NOI18N
        jTextAreaReview.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaReview.setLineWrap(true);
        jTextAreaReview.setRows(5);
        jTextAreaReview.setText("The quick brown fox jumps over the lazy dog whatever now");
        jTextAreaReview.setBorder(null);
        jTextAreaReview.setHighlighter(null);
        jTextAreaReview.setOpaque(false);
        jScrollPane1.setViewportView(jTextAreaReview);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 380, 220));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gradient-red-linear-black-1366x768-c2-8b0000-000000-a-270-f-14.png"))); // NOI18N
        jLabel7.setToolTipText("");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtextUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextUserNameActionPerformed

    private void jtextUserRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextUserRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextUserRateActionPerformed

    private void jButtonNextReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextReviewActionPerformed
//button to get next user rate/review from global result variable resJoin and resName
        try {
            resJoin.next();
            review = resJoin.getString("review");
            rate = resJoin.getInt("userrating");
            uID = resJoin.getInt("userid");

            //set review,rate,count and currentRevPage
            jTextAreaReview.setText(review);
            jtextUserRate.setText(Integer.toString(rate));
            if((currentRevPage+1) <= count){
            jLabeCurrentReview.setText(Integer.toString(++currentRevPage));}

            //this query has to be re written beacuse it depends on the value taken from the previous query
            fetchNameStatement = con.prepareStatement("SELECT name FROM users WHERE id = ?");
            fetchNameStatement.setInt(1, uID);
            resName = fetchNameStatement.executeQuery();

            //set name of user
            resName.next();
            name = resName.getString("name");
            jtextUserName.setText(name);

        } catch (SQLException e) {
           
            
        }

    }//GEN-LAST:event_jButtonNextReviewActionPerformed

    private void jButtonViewReviewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewReviewsActionPerformed
        //button to view reviews of selected movie
        //TODO get index of movie from movie table
        //TODO place this button on the movieTable

        try {
            //join review table and rate table to get review,rate and userid
            joinStatement = con.prepareStatement("SELECT userreview.review, userrating.userrating, userrating.userid"
                    + " FROM userreview INNER JOIN userrating ON userrating.UserID = userreview.UserID"
                    + " WHERE userrating.MovieID = ? AND userreview.MovieID = ?");
            
            joinStatement.setInt(1, movieID);
            joinStatement.setInt(2, movieID);
            resJoin = joinStatement.executeQuery();
            resJoin.next();
            review = resJoin.getString("review");
            rate = resJoin.getInt("userrating");
            uID = resJoin.getInt("userid");
            
            //get count of reviews
            PreparedStatement getCount = con.prepareStatement("SELECT count(*) FROM userreview"
                    + " INNER JOIN userrating ON userrating.UserID = userreview.UserID"
                    + " WHERE userrating.MovieID = ? AND userreview.MovieID = ?");
            getCount.setInt(1, movieID);
            getCount.setInt(2, movieID);
            res = getCount.executeQuery();
            res.next();
            count = res.getInt("COUNT(*)");
            

            //set review,rate,count and currentRevPage
            jTextAreaReview.setText(review);
            jtextUserRate.setText(Integer.toString(rate));
            jLabelReviewCount.setText(Integer.toString(count));
            currentRevPage =1;
            jLabeCurrentReview.setText(Integer.toString(currentRevPage));

            //get username from user table
            fetchNameStatement = con.prepareStatement("SELECT name FROM users WHERE id = ?");
            fetchNameStatement.setInt(1, uID);
            resName = fetchNameStatement.executeQuery();

            //set name of user
            resName.next();
            name = resName.getString("name");
            jtextUserName.setText(name);

        } catch (SQLException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButtonViewReviewsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRevRateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRevRateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRevRateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRevRateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserRevRateView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNextReview;
    private javax.swing.JButton jButtonViewReviews;
    private javax.swing.JLabel jLabeCurrentReview;
    private javax.swing.JLabel jLabeSlash;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelRate;
    private javax.swing.JLabel jLabelReview;
    private javax.swing.JLabel jLabelReviewCount;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextArea jTextAreaReview;
    private javax.swing.JTextField jtextUserName;
    private javax.swing.JTextField jtextUserRate;
    // End of variables declaration//GEN-END:variables
}
