package ProjectPackage;


import static DataBase.Database.Connect;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author OSM
 */
public class RegisterLoginWindow extends javax.swing.JFrame {

    /**
     * Creates new form registerLogin
     */
    public RegisterLoginWindow() {
        initComponents();
          getConnection();
        // make background transparent
        userNameTf.setBackground(new java.awt.Color(0,0,0,1));
        passPf.setBackground(new java.awt.Color(0,0,0,1));
    }
  Connection con;
    Statement stat;
    ResultSet res;

  /*  
     void getConnection() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema", "Mohab", "qwa220zxs18MN313");
            //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema", "root", "root");
        } catch (SQLException e) {
            e.printStackTrace();
        }
        System.out.println("connected");
    }
    */
     private void getConnection(){
    this.con = Connect();
    }
    
     
       public void close() {

        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);

    }
       
       
     public int checkUsername(String username)
    {
        if(username.equals(""))
        {
            return 0;
        }
        return 1;
    }
    
    public int checkUsernameLength(String username)
    {
        if(username.length() < 3 || username.length() > 18)
        {
            return 0;
        }
        return 1;
    }
    
    public int checkPassword(String password)
    {
        if(password.equals(""))
        {
            return 0;
        }
        return 1;
    }
    
    public int checkPasswordLength(String password)
    {
        if(password.length() < 3 || password.length() > 6)
        {
            return 0;
        }
        return 1;
    }   
       
       
       
    int verifyUser(String username, String password)
    {
        int userId = 0 ;
        
        try 
        {
           
             stat = con.createStatement();
             res = stat.executeQuery("SELECT ID, Name, password FROM users");
            while(res.next())
            {
                if((username.equals(res.getString("Name"))) && (password.equals(res.getString("password"))))  
                {
                    userId = res.getInt("ID");
                }
            }
        }
        catch(SQLException ex) 
        {
            Logger.getLogger(RegisterLoginWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        return userId;
    }
       
    public int verifyAdmin(String adminName, String password)
    {
        String fullAdminName, firstNamePart = "admin_";
        int adminId = 0;
         try 
        {
            
            stat = con.createStatement();
            res = stat.executeQuery("SELECT adminID, admin_name, password FROM admins");
            while(res.next())
            {
                fullAdminName = firstNamePart + res.getString("Admin_name");
                if( (adminName.equals(fullAdminName)) && (password.equals(res.getString("password"))) )
                {
                  adminId = res.getInt("adminID");  
                }
            }
        }
        catch(SQLException ex) 
        {
            Logger.getLogger(RegisterLoginWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        return adminId;
    }   

       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelPassword = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelRegister = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        userNameTf = new javax.swing.JTextField();
        passPf = new javax.swing.JPasswordField();
        jButtonRegister = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPassword.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword.setText("Password");
        jPanel2.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, -1, -1));

        jLabelTitle.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Movie Choice");
        jPanel2.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        jLabelRegister.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelRegister.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Register.png"))); // NOI18N
        jLabelRegister.setText("Don't have an account? register here.");
        jLabelRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegisterMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, -1, -1));

        jLabelUserName.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabelUserName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserName.setText("User Name");
        jPanel2.add(jLabelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(200, 200, 200));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 300, -1));

        jSeparator1.setBackground(new java.awt.Color(200, 200, 200));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 260, 30));

        jSeparator3.setBackground(new java.awt.Color(200, 200, 200));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 290, 30));

        jSeparator4.setBackground(new java.awt.Color(200, 200, 200));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 290, -1));

        userNameTf.setFont(new java.awt.Font("SansSerif", 3, 16)); // NOI18N
        userNameTf.setForeground(new java.awt.Color(200, 200, 200));
        userNameTf.setText("Enter User Name");
        userNameTf.setToolTipText("Enter Username");
        userNameTf.setBorder(null);
        userNameTf.setOpaque(false);
        userNameTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameTfFocusGained(evt);
            }
        });
        userNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTfActionPerformed(evt);
            }
        });
        jPanel2.add(userNameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 260, 20));

        passPf.setFont(new java.awt.Font("SansSerif", 3, 16)); // NOI18N
        passPf.setForeground(new java.awt.Color(200, 200, 200));
        passPf.setText("dafdaadafadfafa");
        passPf.setToolTipText("Enter Password");
        passPf.setBorder(null);
        passPf.setOpaque(false);
        passPf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passPfFocusGained(evt);
            }
        });
        passPf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passPfActionPerformed(evt);
            }
        });
        jPanel2.add(passPf, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 260, 20));

        jButtonRegister.setBorder(null);
        jButtonRegister.setContentAreaFilled(false);
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, -1, -1));

        jButtonLogin.setBackground(new java.awt.Color(255, 102, 0));
        jButtonLogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login.png"))); // NOI18N
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 180, 40));
        jButtonLogin.setContentAreaFilled(true);
        jButtonLogin.setFocusPainted(false);
        jButtonLogin.setBorderPainted(false);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/solid_color_bright_lines_18572_1920x1080.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 380, 560));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/popcorn_jxPqo7aS.jpg"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        int verifiedUserId, verifiedadminId;
        
        String user,pass;
        user = userNameTf.getText();
        pass = passPf.getText();
        verifiedUserId = verifyUser(user, pass);
        verifiedadminId = verifyAdmin(user, pass);
         if(verifiedadminId > 0)
        {
            user = user.substring(6);
            FrameUI profile = new FrameUI();
            profile.LoadControlPanel(profile.adminPanel, user, verifiedadminId, 100);
            profile.removePanels();
            this.setVisible(false);
            profile.setVisible(true);
        }
        else if(verifiedUserId > 0)
        {
            FrameUI profile = new FrameUI();
            profile.LoadControlPanel(profile.UserPanel, user, verifiedUserId,50);
            profile.removePanels();
            this.setVisible(false);
            profile.setVisible(true);
        }
         else
        {
            JOptionPane.showMessageDialog(null, "Wrong Username/Password", "Invalid Info", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        close();
        Registration tableWindow = new Registration();
        tableWindow.setVisible(true);

    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void userNameTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameTfFocusGained
        userNameTf.setText("");
    }//GEN-LAST:event_userNameTfFocusGained

    private void userNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTfActionPerformed

    private void passPfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passPfFocusGained
        passPf.setText("");
    }//GEN-LAST:event_passPfFocusGained

    private void passPfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passPfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passPfActionPerformed

    private void jLabelRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegisterMouseClicked
        Registration r = new Registration();
        this.setVisible(false);
        r.setVisible(true);
    }//GEN-LAST:event_jLabelRegisterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterLoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterLoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterLoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterLoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterLoginWindow().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelRegister;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPasswordField passPf;
    private javax.swing.JTextField userNameTf;
    // End of variables declaration//GEN-END:variables
}
