
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mohab
 */
public class FrameUI extends javax.swing.JFrame {

    /**
     * Creates new form FrameUI
     */
    public FrameUI() {
        initComponents();
        getConnection();
    }

Connection con;
Statement stat;
ResultSet res;

void getConnection() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema", "Mohab", "qwa220zxs18MN313");
        } catch (SQLException e) {
            e.printStackTrace();
        }
        System.out.println("connected");
    }
    
    
    
 public void LoadControlPanel(JPanel panel, String username, int userType)
    {
        base1.removeAll();
        base1.add(panel);
        base1.repaint();
        base1.revalidate();
        if(userType == 50)
        {
            userNameL.setText(username);
        }
        else if(userType == 100)
        {
             adminNameL.setText(username);
        }
       
        
    }
 
 
public void LoadPanel(JPanel panel)
    {
        contentBase.removeAll();
        contentBase.add(panel);
        contentBase.repaint();
        contentBase.revalidate();
    }         

public void removePanels()
{
    contentBase.removeAll();
}
 public class costumPanel extends JPanel
    {
        private BufferedImage image;

        public costumPanel() {
            try 
            {                
                image = ImageIO.read(getClass().getResourceAsStream("/Images/gradient-red-linear-black-1366x768-c2-8b0000-000000-a-270-f-14.png"));
            } 
            catch (Exception ex) 
            {
                System.out.println(ex.toString());
            }
    }
        @Override
        public void paintComponent(Graphics g)
        {
            super.paintComponent(g);
            g.drawImage(image, 0, 0, this);
            
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        base1 = new javax.swing.JLayeredPane();
        adminPanel = new javax.swing.JPanel();
        adminIcon = new javax.swing.JLabel();
        Statistics = new javax.swing.JButton();
        signOutButton = new javax.swing.JButton();
        adminNameL = new javax.swing.JLabel();
        AddDeleteMovieB = new javax.swing.JButton();
        UserPanel = new javax.swing.JPanel();
        userIcon = new javax.swing.JLabel();
        movieTableButton = new javax.swing.JButton();
        signOutButton1 = new javax.swing.JButton();
        userNameL = new javax.swing.JLabel();
        revRateViewB = new javax.swing.JButton();
        revRateSubmitB = new javax.swing.JButton();
        secondaryPanel = new javax.swing.JPanel();
        contentBase = new javax.swing.JLayeredPane();
        backGroundP = new javax.swing.JPanel();
        addDeleteMovieP = new costumPanel();
        backGroundPa = new javax.swing.JPanel();
        movieTableP = new javax.swing.JPanel();
        backGroundP1 = new javax.swing.JPanel();
        reviewRatingSubmitP = new costumPanel();
        backGroundP2 = new javax.swing.JPanel();
        reviewRatingViewP = new costumPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(0, 255, 0));

        base1.setLayout(new java.awt.CardLayout());

        adminPanel.setBackground(new java.awt.Color(51, 51, 51));

        adminIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/admin.png"))); // NOI18N

        Statistics.setBackground(new java.awt.Color(255, 153, 0));
        Statistics.setText("Statistics");
        Statistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatisticsActionPerformed(evt);
            }
        });

        signOutButton.setBackground(new java.awt.Color(255, 153, 0));
        signOutButton.setText("Sign Out");
        signOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutButtonActionPerformed(evt);
            }
        });

        adminNameL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adminNameL.setForeground(new java.awt.Color(255, 255, 255));
        adminNameL.setText("Admin name");

        AddDeleteMovieB.setBackground(new java.awt.Color(255, 153, 0));
        AddDeleteMovieB.setText("Add/Delete Movie");
        AddDeleteMovieB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDeleteMovieBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(adminIcon))
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(signOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Statistics, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminNameL, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddDeleteMovieB, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(adminNameL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(AddDeleteMovieB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Statistics, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        base1.add(adminPanel, "card3");

        UserPanel.setBackground(new java.awt.Color(51, 51, 51));

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Userm.png"))); // NOI18N

        movieTableButton.setBackground(new java.awt.Color(255, 153, 0));
        movieTableButton.setText("Movies Table");
        movieTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieTableButtonActionPerformed(evt);
            }
        });

        signOutButton1.setBackground(new java.awt.Color(255, 153, 0));
        signOutButton1.setText("Sign Out");
        signOutButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutButton1ActionPerformed(evt);
            }
        });

        userNameL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userNameL.setForeground(new java.awt.Color(255, 255, 255));
        userNameL.setText("Username");

        revRateViewB.setBackground(new java.awt.Color(255, 153, 0));
        revRateViewB.setText("Review/Rating view");
        revRateViewB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revRateViewBActionPerformed(evt);
            }
        });

        revRateSubmitB.setBackground(new java.awt.Color(255, 153, 0));
        revRateSubmitB.setText("Review/Rating submit");
        revRateSubmitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revRateSubmitBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UserPanelLayout = new javax.swing.GroupLayout(UserPanel);
        UserPanel.setLayout(UserPanelLayout);
        UserPanelLayout.setHorizontalGroup(
            UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(UserPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(revRateSubmitB, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(revRateViewB, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signOutButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameL, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        UserPanelLayout.setVerticalGroup(
            UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(userNameL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(movieTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(revRateSubmitB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(revRateViewB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signOutButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        base1.add(UserPanel, "card2");

        secondaryPanel.setBackground(new java.awt.Color(255, 255, 0));

        contentBase.setLayout(new java.awt.CardLayout());

        backGroundP.setBackground(new java.awt.Color(51, 255, 204));

        javax.swing.GroupLayout addDeleteMoviePLayout = new javax.swing.GroupLayout(addDeleteMovieP);
        addDeleteMovieP.setLayout(addDeleteMoviePLayout);
        addDeleteMoviePLayout.setHorizontalGroup(
            addDeleteMoviePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        addDeleteMoviePLayout.setVerticalGroup(
            addDeleteMoviePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backGroundPLayout = new javax.swing.GroupLayout(backGroundP);
        backGroundP.setLayout(backGroundPLayout);
        backGroundPLayout.setHorizontalGroup(
            backGroundPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backGroundPLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(addDeleteMovieP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        backGroundPLayout.setVerticalGroup(
            backGroundPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backGroundPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addDeleteMovieP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        contentBase.add(backGroundP, "card2");

        backGroundPa.setBackground(new java.awt.Color(153, 153, 0));

        javax.swing.GroupLayout movieTablePLayout = new javax.swing.GroupLayout(movieTableP);
        movieTableP.setLayout(movieTablePLayout);
        movieTablePLayout.setHorizontalGroup(
            movieTablePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        movieTablePLayout.setVerticalGroup(
            movieTablePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backGroundPaLayout = new javax.swing.GroupLayout(backGroundPa);
        backGroundPa.setLayout(backGroundPaLayout);
        backGroundPaLayout.setHorizontalGroup(
            backGroundPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backGroundPaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(movieTableP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        backGroundPaLayout.setVerticalGroup(
            backGroundPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backGroundPaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(movieTableP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        contentBase.add(backGroundPa, "card3");

        javax.swing.GroupLayout reviewRatingSubmitPLayout = new javax.swing.GroupLayout(reviewRatingSubmitP);
        reviewRatingSubmitP.setLayout(reviewRatingSubmitPLayout);
        reviewRatingSubmitPLayout.setHorizontalGroup(
            reviewRatingSubmitPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        reviewRatingSubmitPLayout.setVerticalGroup(
            reviewRatingSubmitPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backGroundP1Layout = new javax.swing.GroupLayout(backGroundP1);
        backGroundP1.setLayout(backGroundP1Layout);
        backGroundP1Layout.setHorizontalGroup(
            backGroundP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backGroundP1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(reviewRatingSubmitP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        backGroundP1Layout.setVerticalGroup(
            backGroundP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backGroundP1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reviewRatingSubmitP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentBase.add(backGroundP1, "card4");

        backGroundP2.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout reviewRatingViewPLayout = new javax.swing.GroupLayout(reviewRatingViewP);
        reviewRatingViewP.setLayout(reviewRatingViewPLayout);
        reviewRatingViewPLayout.setHorizontalGroup(
            reviewRatingViewPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        reviewRatingViewPLayout.setVerticalGroup(
            reviewRatingViewPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backGroundP2Layout = new javax.swing.GroupLayout(backGroundP2);
        backGroundP2.setLayout(backGroundP2Layout);
        backGroundP2Layout.setHorizontalGroup(
            backGroundP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backGroundP2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(reviewRatingViewP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        backGroundP2Layout.setVerticalGroup(
            backGroundP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backGroundP2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reviewRatingViewP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentBase.add(backGroundP2, "card5");

        javax.swing.GroupLayout secondaryPanelLayout = new javax.swing.GroupLayout(secondaryPanel);
        secondaryPanel.setLayout(secondaryPanelLayout);
        secondaryPanelLayout.setHorizontalGroup(
            secondaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentBase, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        secondaryPanelLayout.setVerticalGroup(
            secondaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentBase)
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(base1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(secondaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(base1)
            .addComponent(secondaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void movieTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieTableButtonActionPerformed
        this.LoadPanel(backGroundPa);
    }//GEN-LAST:event_movieTableButtonActionPerformed

    private void StatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatisticsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatisticsActionPerformed

    private void signOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutButtonActionPerformed
        RegisterLoginWindow loginFrame = new RegisterLoginWindow();
        this.setVisible(false);
        loginFrame.setVisible(true);
    }//GEN-LAST:event_signOutButtonActionPerformed

    private void signOutButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutButton1ActionPerformed
        RegisterLoginWindow loginFrame = new RegisterLoginWindow();
        this.setVisible(false);
        loginFrame.setVisible(true);
    }//GEN-LAST:event_signOutButton1ActionPerformed

    private void AddDeleteMovieBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDeleteMovieBActionPerformed
        this.LoadPanel(backGroundP);
    }//GEN-LAST:event_AddDeleteMovieBActionPerformed

    private void revRateViewBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revRateViewBActionPerformed
        this.LoadPanel(backGroundP2);
    }//GEN-LAST:event_revRateViewBActionPerformed

    private void revRateSubmitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revRateSubmitBActionPerformed
       this.LoadPanel(backGroundP1);
    }//GEN-LAST:event_revRateSubmitBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDeleteMovieB;
    private javax.swing.JButton Statistics;
    public javax.swing.JPanel UserPanel;
    private javax.swing.JPanel addDeleteMovieP;
    private javax.swing.JLabel adminIcon;
    private javax.swing.JLabel adminNameL;
    public javax.swing.JPanel adminPanel;
    public javax.swing.JPanel backGroundP;
    private javax.swing.JPanel backGroundP1;
    private javax.swing.JPanel backGroundP2;
    public javax.swing.JPanel backGroundPa;
    private javax.swing.JLayeredPane base1;
    private javax.swing.JLayeredPane contentBase;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton movieTableButton;
    private javax.swing.JPanel movieTableP;
    private javax.swing.JButton revRateSubmitB;
    private javax.swing.JButton revRateViewB;
    private javax.swing.JPanel reviewRatingSubmitP;
    private javax.swing.JPanel reviewRatingViewP;
    private javax.swing.JPanel secondaryPanel;
    private javax.swing.JButton signOutButton;
    private javax.swing.JButton signOutButton1;
    private javax.swing.JLabel userIcon;
    private javax.swing.JLabel userNameL;
    // End of variables declaration//GEN-END:variables
}
