
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author OSM
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public Registration() {
        initComponents();
        getConnection();
        jPasswordFeild.setBackground(new java.awt.Color(0, 0, 0, 1));
        jTextName.setBackground(new java.awt.Color(0, 0, 0, 1));
    }

    Connection con;
    Statement stat;
    ResultSet res;

    void getConnection() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        try {
            //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema", "Mohab", "qwa220zxs18MN313");
                        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema", "root", "root");

        } catch (SQLException e) {
            e.printStackTrace();
        }
        System.out.println("connected");
    }

    private void addUser(String name , String password) throws SQLException{
                PreparedStatement myStatement = con.prepareStatement("INSERT INTO users (id,name,password) VALUES (DEFAULT,?,?)");
                myStatement.setString(1, name);
                myStatement.setString(2, password);
                myStatement.execute();
    }
    
    public int verfiyName(String name, String password) {

        if ((name.isEmpty() || name == null) || password.isEmpty() || password == null) {
            return 1;
        } else if (name.length() < 3 || name.length() > 12) {
            return 2;
        } else if (password.length() < 3 || password.length() > 6) {
            return 3;
        }
        return 0;
    }    
    
    
    public void close() {

        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);

    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelRegister = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jButtonLogin = new javax.swing.JButton();
        jButtonRegiset = new javax.swing.JButton();
        jLabelPassword = new javax.swing.JLabel();
        jPasswordFeild = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRegister.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabelRegister.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegister.setText("Register:");
        jPanel1.add(jLabelRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabelUserName.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabelUserName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserName.setText("User Name");
        jPanel1.add(jLabelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jTextName.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jTextName.setForeground(new java.awt.Color(255, 255, 255));
        jTextName.setText("Enter User Name");
        jTextName.setBorder(null);
        jTextName.setOpaque(false);
        jTextName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextNameFocusGained(evt);
            }
        });
        jTextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 260, 20));

        jSeparator5.setBackground(new java.awt.Color(200, 200, 200));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 290, 30));

        jSeparator3.setBackground(new java.awt.Color(200, 200, 200));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 290, 30));

        jButtonLogin.setBackground(new java.awt.Color(115, 0, 0));
        jButtonLogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setText("Back");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 180, 40));
        jButtonRegiset.setContentAreaFilled(true);
        jButtonRegiset.setFocusPainted(false);
        jButtonRegiset.setBorderPainted(false);

        jButtonRegiset.setBackground(new java.awt.Color(115, 0, 0));
        jButtonRegiset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonRegiset.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegiset.setText("Register");
        jButtonRegiset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisetActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegiset, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 180, 40));
        jButtonRegiset.setContentAreaFilled(true);
        jButtonRegiset.setFocusPainted(false);
        jButtonRegiset.setBorderPainted(false);

        jLabelPassword.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword.setText("Password");
        jPanel1.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jPasswordFeild.setFont(new java.awt.Font("SansSerif", 3, 16)); // NOI18N
        jPasswordFeild.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordFeild.setText("dafdaadafadfafa");
        jPasswordFeild.setBorder(null);
        jPasswordFeild.setOpaque(false);
        jPasswordFeild.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFeildFocusGained(evt);
            }
        });
        jPasswordFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFeildActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 260, 20));

        jSeparator4.setBackground(new java.awt.Color(200, 200, 200));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 290, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gradient-red-linear-black-1366x768-c2-8b0000-000000-a-270-f-14.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 560));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNameFocusGained
        jTextName.setText("");
    }//GEN-LAST:event_jTextNameFocusGained

    private void jTextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNameActionPerformed

    private void jPasswordFeildFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFeildFocusGained
        jPasswordFeild.setText("");
    }//GEN-LAST:event_jPasswordFeildFocusGained

    private void jPasswordFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFeildActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        close();
        RegisterLoginWindow registerLoginWindow = new RegisterLoginWindow();
        registerLoginWindow.setVisible(true);
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonRegisetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisetActionPerformed

        
            String name;
            String password;

            name = jTextName.getText();
            password = jPasswordFeild.getText();

            int code = verfiyName(name, password);
            
            //check if any of the feilds are empty
        switch (code) {

            case 1:
                JOptionPane.showMessageDialog(null,
                        "Please fill both feilds",
                        "Missing information",
                        JOptionPane.ERROR_MESSAGE);
                break;

            case 2:
                JOptionPane.showMessageDialog(null,
                        "name must be between 3 and 12 characters",
                        "User Info error",
                        JOptionPane.ERROR_MESSAGE);

                break;
                
            case 3:
                JOptionPane.showMessageDialog(null,
                        "Password must be between 3 and 6 characters",
                        "User Info error",
                        JOptionPane.ERROR_MESSAGE);

                break;
            
            case 0:

        try {

                addUser(name, password);

                JOptionPane.showMessageDialog(null,
                        "Successfully Registered!",
                        "Success",
                        JOptionPane.DEFAULT_OPTION);

            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null,
                        "User name is already taken.",
                        "User name is taken",
                        JOptionPane.ERROR_MESSAGE);
            }
            break;
        }
    }//GEN-LAST:event_jButtonRegisetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonRegiset;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelRegister;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFeild;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextName;
    // End of variables declaration//GEN-END:variables
}
