
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author OSM
 */
public class RegisterLoginWindow extends javax.swing.JFrame {

    /**
     * Creates new form registerLogin
     */
    public RegisterLoginWindow() {
        initComponents();
          getConnection();
        // make background transparent
        userNameTf.setBackground(new java.awt.Color(0,0,0,1));
        passTf.setBackground(new java.awt.Color(0,0,0,1));
    }
  Connection con;
    Statement stat;
    ResultSet res;

    
     void getConnection() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema", "Mohab", "qwa220zxs18MN313");
        } catch (SQLException e) {
            e.printStackTrace();
        }
        System.out.println("connected");
    }
     
       public void close() {

        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);

    }
       
       
       
       
       int verifyUser(String username, String password)
    {
        int userType = 1;
        
        try 
        {
           
            stat = con.createStatement();
             res = stat.executeQuery("SELECT Name,password FROM users");
            while(res.next())
            {
                if((username.equals(res.getString("Name"))) && (password.equals("admin")))  
                {
                    userType = 100;  // 50 refers to regular user
                }
                else if((username.equals(res.getString("Name"))) && (password.equals(res.getString("password"))))
                {
                    userType = 50;   // 100 refers to admin user
                }
            }
        }
        catch(SQLException ex) 
        {
            Logger.getLogger(RegisterLoginWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        return userType;
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelPassword = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelRegister = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        userNameTf = new javax.swing.JTextField();
        passTf = new javax.swing.JTextField();
        jButtonRegister = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(765, 560));
        setResizable(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPassword.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword.setText("Password");
        jPanel2.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, -1, -1));

        jLabelTitle.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Movie Choice");
        jPanel2.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        jLabelRegister.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelRegister.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegister.setText("Don't have an account? register here.");
        jPanel2.add(jLabelRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, -1, -1));

        jLabelUserName.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabelUserName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserName.setText("User Name");
        jPanel2.add(jLabelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(200, 200, 200));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 300, -1));

        jSeparator1.setBackground(new java.awt.Color(200, 200, 200));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 260, 30));

        jSeparator3.setBackground(new java.awt.Color(200, 200, 200));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 290, 30));

        jSeparator4.setBackground(new java.awt.Color(200, 200, 200));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 290, -1));

        userNameTf.setFont(new java.awt.Font("SansSerif", 3, 16)); // NOI18N
        userNameTf.setForeground(new java.awt.Color(200, 200, 200));
        userNameTf.setText("Enter User Name");
        userNameTf.setBorder(null);
        userNameTf.setOpaque(false);
        userNameTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameTfFocusGained(evt);
            }
        });
        userNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTfActionPerformed(evt);
            }
        });
        jPanel2.add(userNameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 260, 20));

        passTf.setFont(new java.awt.Font("SansSerif", 3, 16)); // NOI18N
        passTf.setForeground(new java.awt.Color(200, 200, 200));
        passTf.setText("Enter Password");
        passTf.setBorder(null);
        passTf.setOpaque(false);
        passTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passTfFocusGained(evt);
            }
        });
        passTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTfActionPerformed(evt);
            }
        });
        jPanel2.add(passTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 260, 20));

        jButtonRegister.setBorder(null);
        jButtonRegister.setContentAreaFilled(false);
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, -1, -1));

        jButtonLogin.setBackground(new java.awt.Color(255, 102, 0));
        jButtonLogin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(200, 200, 200));
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 180, 40));
        jButtonLogin.setContentAreaFilled(true);
        jButtonLogin.setFocusPainted(false);
        jButtonLogin.setBorderPainted(false);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/167.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 380, 560));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/popcorn_jxPqo7aS.jpg"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        int verifiedUserType = 0;
        String user,pass;
        user = userNameTf.getText();
        pass = passTf.getText();
        verifiedUserType = verifyUser(user, pass);
         if(verifiedUserType== 50)
        {
            FrameUI profile = new FrameUI();
            profile.LoadControlPanel(profile.UserPanel, user, 50);
            this.setVisible(false);
            profile.setVisible(true);
        }
        else if(verifiedUserType == 100)
        {
            FrameUI profile = new FrameUI();
            profile.LoadControlPanel(profile.adminPanel, user, 100);
            this.setVisible(false);
            profile.setVisible(true);
        }
         else
        {
            JOptionPane.showMessageDialog(null, "Wrong Username/Password", "Invalid Info", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void passTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTfActionPerformed

    private void passTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passTfFocusGained
        passTf.setText("");
    }//GEN-LAST:event_passTfFocusGained

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        close();
        Registration tableWindow = new Registration();
        tableWindow.setVisible(true);

    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void userNameTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameTfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTfFocusGained

    private void userNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterLoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterLoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterLoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterLoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterLoginWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelRegister;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField passTf;
    private javax.swing.JTextField userNameTf;
    // End of variables declaration//GEN-END:variables
}
